# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eigenschaft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Substanz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=200)),
                ('name_botanisch', models.CharField(max_length=200)),
                ('kaufdatum', models.DateTimeField(verbose_name='Kaufdatum')),
                ('preispergramm', models.IntegerField(default=0, verbose_name='Preis pro Gramm')),
                ('eigenschaften', models.ManyToManyField(to='rauch.Eigenschaft')),
            ],
        ),
    ]
